data:
  name: cve
  args:
    cve_file: # cve file name if it is already downloaded
    cache_dir: "data/cache" # directory where cve file is downloaded or to be downloaded
    # None or isoformat string e.g. YYYY-MM-DD, if cve_file is None, defaults to 121 days before the current utc
    lastModStartDate: "2023-07-01"
    # None or isoformat string e.g. YYYY-MM-DD, if cve_file is None, defaults to 1 day before the current utc
    lastModEndDate: "2023-07-31"
    overwrite_existing: false # if true and cve_file is None, redownload
    api_sleep_seconds: 6 # sleep seconds between NVD api call

index:
  name: hfst
  init_args:
    index_encoder: all-mpnet-base-v2 # to create index
    query_encoder: # to encode query, defaults to index_encoder
    index_src_col: descriptions # text col name on which index to create
    index_col_name: embeddings # col name for index embeddings
    overwrite_existing: false # set True to force rebuilding of index
  search_args:
    k: 10 # number of searches to return as k-nearest neighbours